---
abstract: 'A container for functions of the ClusterSSH programs'
author:
  - 'Duncan Ferguson <duncan_j_ferguson@yahoo.co.uk>'
build_requires:
  File::Temp: 0
  File::Which: 0
  Readonly: 0
  Test::Differences: 0
  Test::DistManifest: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Trap: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ClusterSSH
provides:
  App::ClusterSSH:
    file: lib/App/ClusterSSH.pm
    version: 4.01_04
  App::ClusterSSH::Base:
    file: lib/App/ClusterSSH/Base.pm
    version: 0.02
  App::ClusterSSH::Cluster:
    file: lib/App/ClusterSSH/Cluster.pm
    version: 0.01
  App::ClusterSSH::Config:
    file: lib/App/ClusterSSH/Config.pm
    version: 0.02
  App::ClusterSSH::Helper:
    file: lib/App/ClusterSSH/Helper.pm
    version: 0.02
  App::ClusterSSH::Host:
    file: lib/App/ClusterSSH/Host.pm
    version: 0.03
  App::ClusterSSH::L10N:
    file: lib/App/ClusterSSH/L10N.pm
    version: 0
  App::ClusterSSH::L10N::en:
    file: lib/App/ClusterSSH/L10N/en.pm
    version: 0
requires:
  Exception::Class: 1.31
  Locale::Maketext: 0
  Tk: 800.022
  Try::Tiny: 0
  X11::Protocol: 0.56
  version: 0
resources:
  bugtracker: http://sourceforge.net/tracker/?group_id=89139
  homepage: http://clusterssh.sourceforge.net/
  license: http://dev.perl.org/licenses/
  x_Repository:
    - http://clusterssh.git.sourceforge.net/
    - http://github.com/duncs/clusterssh
version: 4.01_04
