---
name: App-ClusterSSH
version: 4.00_01
author: []
abstract: The great new App::ClusterSSH!
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Tk: 800.022
  X11::Protocol: 0.56
  version: 0
provides:
  App::ClusterSSH:
    file: lib/App/ClusterSSH.pm
    version: 4.00_01
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
